# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geodiversity Calculator
                                 A QGIS plugin
 This plugin writes a grid over a custom polygon.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-05
        copyright            : (C) 2021 by Marton Pal
        email                : marchello@map.elte.hu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeodiversityCalculator class from file GeodiversityCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geodiversity_calculator import  GeodiversityCalculator
    return GeodiversityCalculator(iface)
